// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nuflnieornkewbghrhgb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im51ZmxuaWVvcm5rZXdiZ2hyaGdiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMjA3OTcsImV4cCI6MjA2NTg5Njc5N30.0hXA2zpF8smDpP95TfAPK7rN8uwopVmhCSx-1N5vMPg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);